Update assemble

diff --git a/nodejs-helloworld-s2i-scripts/.s2i/bin/assemble b/nodejs-helloworld-s2i-scripts/.s2i/bin/assemble
--- a/nodejs-helloworld-s2i-scripts/.s2i/bin/assemble
+++ b/nodejs-helloworld-s2i-scripts/.s2i/bin/assemble
@@ -20,4 +20,18 @@ echo -e "\n\n"
 
 echo -e "\n\n   ... calling '/usr/libexec/s2i/assemble' from builder image ...\n\n"
 /usr/libexec/s2i/assemble
+
+rc=$?
+
 echo -e "\n\n   *** back to 'assemble' script from .s2i/bin folder of 'nodejs-helloworld-s2i-scripts' project ***\n\n"
+
+echo -e "\n\n   *** test result code for call to '/usr/libexec/s2i/assemble' ***\n\n"
+
+if [ $rc -eq 0 ]; then
+    echo "The S2I build completed successfully."
+else
+    echo "The S2I build failed !!!"
+fi
+
+# exit with result code from inner build
+exit $rc
